### ISSUE TITLE
intermitent bug when sending blobs on node 0.12.7

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/rhizome#104]
```
  rhizome.server.connections send /sample/1 [W7fDUHlFs7jHT4Xw,Blob(768044)] +9s
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: send EMSGSIZE
    at exports._errnoException (util.js:746:11)
    at SendWrap.afterSend [as oncomplete] (dgram.js:348:23)
vasv1005:rhizome-app valvoja$ nvm
```

Maybe could be solved with #35 ?

**Comment by sebpiq** [comment]
Blob size too big should not happen with TCP. Now there is a test for these.
