### ISSUE TITLE
deploy rhizome on now zeit's now 

### ISSUE THREAD

**Issue by tatecarson** [sebpiq/rhizome#137]
Hi, 

I'm trying to get rhizome running on now, I'm not sure if you have any experience with it. I had previously gotten it running on AWS EC2 but I want to find an easier option because 1) It took me forever to figure out how to get it to work 2) I don't really understand it and keep getting charged 3) I really want to be able to teach someone how to deploy so they can start to use rhizome for there work. 

i'm starting with the base example and my package.json file is: 
```
{
  "name": "base",
  "version": "1.0.0",
  "description": "Instructions --------------",
  "main": "config.js",
  "scripts": {
    "start": "node node_modules/rhizome/bin/main.js config.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "rhizome": "^0.3.0"
  }
}
```
Does this look correct? I tried with just rhizome config.js in the start section but I remember you mentioning to try this longer one but neither work. 

Here's the error that I get: 
```
tate-2:base tatecarson$ now
> Deploying ~/Desktop/base
> Using Node.js 7.7.3 (default)
> Ready! https://base-kabrvwkfsh.now.sh (copied to clipboard) [904ms]
> You are on the OSS plan. Your code will be made public.
> Upload [====================] 100% 0.0s
> Sync complete (344B) [2s]
> Initializing…
> Building
> ▲ npm install
> ⧗ Installing:
>  ‣ rhizome@^0.3.0
> ✓ Installed 2 modules [560ms]

> ▲ npm start
> > base@1.0.0 start /home/nowuser/src
> > node node_modules/rhizome/bin/main.js config.js
> module.js:472
>     throw err;
>     ^
> Error: Cannot find module '/home/nowuser/src/node_modules/rhizome/bin/main.js'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:425:7)
>     at startup (bootstrap_node.js:146:9)
>     at bootstrap_node.js:540:3
> npm ERR! Linux 4.7.0-coreos
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
> npm ERR! node v7.7.3
> npm ERR! npm  v4.1.2
> npm ERR! code ELIFECYCLE
> npm ERR! base@1.0.0 start: `node node_modules/rhizome/bin/main.js config.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the base@1.0.0 start script 'node node_modules/rhizome/bin/main.js config.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the base package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node node_modules/rhizome/bin/main.js config.js

> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs base
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls base
> npm ERR! There is likely additional logging output above.
> npm ERR! Linux 4.7.0-coreos
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
> npm ERR! node v7.7.3
> npm ERR! npm  v4.1.2
> npm ERR! path npm-debug.log.3624018928
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall open
> npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.3624018928'
> npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.3624018928'
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'open',
> npm ERR!   path: 'npm-debug.log.3624018928' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/nowuser/src/npm-debug.log
> No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
```
Any ideas on why this fails? Or, another idea for a simpler deployment that I can easily explain to someone new to this kind of thing? 

thanks again.

**Comment by sebpiq** [comment]
Hi @tatecarson ! Sorry for the super slow answer. This error means that the user you run rhizome with tries to access a file and doesn't have the permissions for that ... so this really depends on your environment. What is "now" ?

**Comment by tatecarson** [comment]
It's a really simple deployment platform: https://zeit.co/now . Much easier than dealing with EC2 or anything else like that, but it looks like it doesn't give you enough control for rhizome.

**Comment by sebpiq** [comment]
Ok Ill have a look!

**Comment by sebpiq** [comment]
I gave some thinking into how to do this, and I think the best way is to make rhizome available as a docker image! As soon as I find time, I'll do a big refactor to clean the code base, and dockerize it, so it's easy to deploy anywhere ...

**Comment by tatecarson** [comment]
Here's an example myself and Jesse Allison have come up with to turn rhizome into a docker image. It runs on now fine but now only allows one port to be open at a time so OSC communication does not work. If OSC communication isn't needed now seems like a great solution.
